Repository siga-fab/cca-fab-components, pull requests merged in 2020-10, with the labels that each got.

#30 feat(common-textarea): adiciona novo componente de textarea. concluido
  projects/common/src/lib/textarea/textarea.component.html
  projects/common/src/lib/textarea/textarea.component.scss
  projects/common/src/lib/textarea/textarea.component.spec.ts
  projects/common/src/lib/textarea/textarea.component.ts
  projects/common/src/lib/textarea/textarea.module.ts
  projects/common/src/public-api.ts
  src/stories/common/Input.stories.ts
  src/stories/common/Textarea.stories.ts
Labels: aprimoramento

#31 feat(common-autocomplete, common-select, common-input): adiciona componentes e recursos faltantes para total integração com Reactive Forms
  projects/common/src/assets/scss/colors.scss
  projects/common/src/lib/autocomplete/autocomplete.component.html
  projects/common/src/lib/autocomplete/autocomplete.component.scss
  projects/common/src/lib/autocomplete/autocomplete.component.spec.ts
  projects/common/src/lib/autocomplete/autocomplete.component.ts
  projects/common/src/lib/autocomplete/autocomplete.module.ts
  projects/common/src/lib/button/button.component.html
  projects/common/src/lib/button/button.component.scss
  projects/common/src/lib/card/card.component.scss
  projects/common/src/lib/dropmenu/dropmenu-item.component.html
  projects/common/src/lib/dropmenu/dropmenu-item.component.scss
  projects/common/src/lib/dropmenu/dropmenu-item.component.spec.ts
  projects/common/src/lib/dropmenu/dropmenu-item.component.ts
  projects/common/src/lib/dropmenu/dropmenu.component.spec.ts
  projects/common/src/lib/dropmenu/dropmenu.module.ts
  projects/common/src/lib/form/form-section.component.html
  projects/common/src/lib/icon/icon.component.html
  projects/common/src/lib/icon/icon.component.scss
  projects/common/src/lib/input/input.component.html
  projects/common/src/lib/input/input.component.scss
  projects/common/src/lib/input/input.component.spec.ts
  projects/common/src/lib/input/input.component.ts
  projects/common/src/lib/select/select.component.html
  projects/common/src/lib/select/select.component.scss
  projects/common/src/lib/select/select.component.spec.ts
  projects/common/src/lib/select/select.component.ts
  projects/common/src/lib/select/select.module.ts
  projects/common/src/lib/table/table.component.html
  projects/common/src/lib/table/table.component.ts
  projects/common/src/public-api.ts
  projects/common/src/types/ngForms.ts
  projects/common/src/types/select.ts
  src/stories/common/Autocomplete.stories.ts
  src/stories/common/Form.stories.ts
  src/stories/common/Icon.stories.ts
  src/stories/common/Input.stories.ts
  src/stories/common/Select.stories.ts
  src/stories/common/Textarea.stories.ts
Labels: aprimoramento

#35 feat(common-input, common-table, common-textarea): Adiciona novas features em input e tabela e altera textarea de acordo com modificações feitas em input
  projects/common/src/lib/input/input.component.html
  projects/common/src/lib/input/input.component.scss
  projects/common/src/lib/input/input.component.ts
  projects/common/src/lib/table/table.component.ts
  projects/common/src/lib/textarea/textarea.component.html
  projects/common/src/lib/textarea/textarea.component.scss
  projects/common/src/lib/textarea/textarea.component.ts
  src/stories/common/Input.stories.ts
  src/stories/common/Table.stories.ts
  src/stories/common/Textarea.stories.ts
Labels: aprimoramento

#36 feat(common-modal): adiciona componente de modal
  projects/common/src/lib/card/card.component.scss
  projects/common/src/lib/modal/modal.component.html
  projects/common/src/lib/modal/modal.component.scss
  projects/common/src/lib/modal/modal.component.spec.ts
  projects/common/src/lib/modal/modal.component.ts
  projects/common/src/lib/modal/modal.module.ts
  projects/common/src/public-api.ts
  src/stories/common/Modal.stories.ts
Labels: aprimoramento

#39 style(common-button): adiciona estilo de confirmação ao botão e as re…
  projects/common/src/lib/button/button.component.html
  projects/common/src/lib/button/button.component.scss
  projects/common/src/lib/button/button.component.ts
  src/stories/common/Button.stories.ts
Labels: aprimoramento

#40 feat(common-select): adiciona feature de acessibilidade para select, …
  projects/common/src/lib/select/select.component.html
  projects/common/src/lib/select/select.component.spec.ts
  projects/common/src/lib/select/select.component.ts
  projects/common/src/lib/textarea/textarea.component.scss
Labels: aprimoramento

#44 feat(common-lib): ajustes visuais generalistas e adição de estilos
  projects/common/src/lib/autocomplete/autocomplete.component.scss
  projects/common/src/lib/form/form.component.html
  projects/common/src/lib/form/form.component.ts
  projects/common/src/lib/select/select.component.scss
  projects/common/src/lib/tag/tag.component.html
  projects/common/src/lib/tag/tag.component.scss
  projects/common/src/lib/tag/tag.component.ts
  src/stories/common/Tag.stories.ts
Labels: aprimoramento

#45 style(common-autocomplete, common-select): altera opacidade de campo …
  projects/common/src/lib/autocomplete/autocomplete.component.scss
  projects/common/src/lib/select/select.component.scss
Labels: aprimoramento

#46 feat(common-tag): adiciona feature de exclusão/fechamento de tag
  projects/common/src/lib/tag/tag.component.html
  projects/common/src/lib/tag/tag.component.scss
  projects/common/src/lib/tag/tag.component.spec.ts
  projects/common/src/lib/tag/tag.component.ts
  projects/common/src/lib/tag/tag.module.ts
  src/stories/common/Tag.stories.ts
Labels: aprimoramento

#48 fix(common-lib): corrige comportamento errático em componentes desabilitados
  projects/common/src/lib/button/button.component.scss
  projects/common/src/lib/input/input.component.html
  projects/common/src/lib/select/select.component.html
  projects/common/src/lib/textarea/textarea.component.html
  projects/common/src/lib/textarea/textarea.component.scss
  projects/common/src/lib/textarea/textarea.component.ts
Labels: aprimoramento

#49 fix(common-select, common-autocomplete, common-table, common-input): corrige erros de estilo…
  projects/common/src/lib/autocomplete/autocomplete.component.scss
  projects/common/src/lib/button/button.component.ts
  projects/common/src/lib/input/input.component.scss
  projects/common/src/lib/select/select.component.scss
  projects/common/src/lib/table/table.component.scss
  projects/common/src/lib/table/table.component.ts
Labels: bug

#50 fix(common-lib): corrige bugs e incoerências de estilo em diversos componentes
  projects/common/src/lib/autocomplete/autocomplete.component.scss
  projects/common/src/lib/form/form.component.ts
  projects/common/src/lib/modal/modal.component.html
  projects/common/src/lib/modal/modal.component.scss
  projects/common/src/lib/modal/modal.component.ts
  projects/common/src/lib/select/select.component.scss
  projects/common/src/lib/tag/tag.component.scss
Labels: bug

#55 feat(common-file-uploader): adiciona componente de file uploader
  projects/common/src/lib/button/button.component.scss
  projects/common/src/lib/checkbox/checkbox.component.scss
  projects/common/src/lib/dropmenu/dropmenu.component.scss
  projects/common/src/lib/file-uploader/file-uploader.component.html
  projects/common/src/lib/file-uploader/file-uploader.component.scss
  projects/common/src/lib/file-uploader/file-uploader.component.spec.ts
  projects/common/src/lib/file-uploader/file-uploader.component.ts
  projects/common/src/lib/file-uploader/file-uploader.module.ts
  projects/common/src/lib/input/input.component.scss
  projects/common/src/lib/modal/modal.component.html
  projects/common/src/lib/modal/modal.component.scss
  projects/common/src/lib/modal/modal.component.ts
  projects/common/src/lib/select/select.component.ts
  projects/common/src/lib/table/table.component.html
  projects/common/src/lib/table/table.component.scss
  projects/common/src/lib/table/table.component.ts
  projects/common/src/public-api.ts
  projects/common/tsconfig.lib.json
  src/stories/common/FileUploader.stories.ts
  src/stories/common/Modal.stories.ts
  tsconfig.json
Labels: aprimoramento

#56 feat(common-file-uploader): adiciona componente de file uploader (file input)
  projects/common/src/lib/button/button.component.scss
  projects/common/src/lib/checkbox/checkbox.component.scss
  projects/common/src/lib/dropmenu/dropmenu.component.scss
  projects/common/src/lib/file-uploader/file-uploader.component.html
  projects/common/src/lib/file-uploader/file-uploader.component.scss
  projects/common/src/lib/file-uploader/file-uploader.component.spec.ts
  projects/common/src/lib/file-uploader/file-uploader.component.ts
  projects/common/src/lib/file-uploader/file-uploader.module.ts
  projects/common/src/lib/input/input.component.scss
  projects/common/src/lib/input/input.component.spec.ts
  projects/common/src/lib/input/input.component.ts
  projects/common/src/lib/modal/modal.component.html
  projects/common/src/lib/modal/modal.component.scss
  projects/common/src/lib/modal/modal.component.ts
  projects/common/src/lib/select/select.component.html
  projects/common/src/lib/select/select.component.scss
  projects/common/src/lib/select/select.component.ts
  projects/common/src/lib/table/table.component.html
  projects/common/src/lib/table/table.component.scss
  projects/common/src/lib/table/table.component.ts
  projects/common/src/public-api.ts
  projects/common/tsconfig.lib.json
  src/stories/common/FileUploader.stories.ts
  src/stories/common/Modal.stories.ts
  tsconfig.json
Labels: aprimoramento, bug

#58 fix(common-autocomplete): corrige comportamento errático de autocomplete, criando duas novas props
  projects/common/src/lib/autocomplete/autocomplete.component.spec.ts
  projects/common/src/lib/autocomplete/autocomplete.component.ts
  src/stories/common/Autocomplete.stories.ts
Labels: bug

#59 fix(common-autocomplete): corrige comportamento errático do componente após emissão de confirm
  projects/common/src/lib/autocomplete/autocomplete.component.ts
  projects/common/src/lib/button/button.component.scss
Labels: aprimoramento

#60 hotfix(common-lib): corrige a opacidade do input disabled, props, espaçamento da label e remove os atributos do autocomplete
  projects/common/src/lib/autocomplete/autocomplete.component.html
  projects/common/src/lib/autocomplete/autocomplete.component.ts
  projects/common/src/lib/input/input.component.html
  projects/common/src/lib/input/input.component.scss
  projects/common/src/lib/label/label.component.scss
  projects/common/src/lib/select/select.component.html
  projects/common/src/lib/select/select.component.ts
Labels: bug

#62 hotfix(common-lib): refatora o componente de tabela, resolve alguns bugs pontuais e melhora um pouco a documentação
  projects/common/src/lib/button/button.component.html
  projects/common/src/lib/button/button.component.ts
  projects/common/src/lib/input/input.component.html
  projects/common/src/lib/input/input.component.scss
  projects/common/src/lib/input/input.component.spec.ts
  projects/common/src/lib/input/input.component.ts
  projects/common/src/lib/select/select.component.ts
  projects/common/src/lib/table/ng-template-name.directive.ts
  projects/common/src/lib/table/table.component.html
  projects/common/src/lib/table/table.component.scss
  projects/common/src/lib/table/table.component.spec.ts
  projects/common/src/lib/table/table.component.ts
  projects/common/src/lib/table/table.module.ts
  projects/common/src/lib/tag/tag.component.ts
  src/stories/common/Autocomplete.stories.ts
  src/stories/common/FileUploader.stories.ts
  src/stories/common/Select.stories.ts
  src/stories/common/Table.stories.mdx
  src/stories/common/Table.stories.ts
  src/stories/common/Textarea.stories.ts
  src/stories/docs/3_Typography.stories.mdx
  src/stories/docs/4_Colors.stories.mdx
  tslint.json
Labels: aprimoramento, bug

#63 fix(common-select, common-input, common-tag): corrige erro ao tratar …
  projects/common/src/lib/input/input.component.scss
  projects/common/src/lib/input/input.component.ts
  projects/common/src/lib/select/select.component.ts
  projects/common/src/lib/tag/tag.component.html
  projects/common/src/lib/tag/tag.component.ts
Labels: bug

#64 fix(common-tag): adiciona estilo de validação
  projects/common/src/lib/tag/tag.component.html
  projects/common/src/lib/tag/tag.component.scss
  projects/common/src/lib/tag/tag.component.ts
  src/stories/common/Tag.stories.ts
Labels: aprimoramento

#65 fix(common-select): corrige comportamento errático ao manipular valor…
  projects/common/src/lib/select/select.component.ts
  src/stories/common/Select.stories.ts
Labels: bug

#66 fix(common-select): corrige comportamento errático do select de invoc…
  projects/common/src/lib/select/select.component.ts
Labels: bug

#67 fix(common-select): corrige comportamento errático quando initialValu…
  projects/common/src/lib/select/select.component.ts
Labels: bug

#68 fix(common-select): corrige comportamento errático ao tentar referenc…
  projects/common/src/lib/select/select.component.ts
Labels: bug
